/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#006e2d',
        'primary-container': '#1db954',
        'primary-fixed': '#72fe8f',
        'primary-fixed-dim': '#53e076',
        'on-primary': '#ffffff',
        'on-primary-container': '#004118',
        'on-primary-fixed': '#002108',
        'on-primary-fixed-variant': '#005320',
        'inverse-primary': '#53e076',
        'secondary': '#466556',
        'secondary-container': '#c5e8d5',
        'secondary-fixed': '#c8ead7',
        'secondary-fixed-dim': '#adcebc',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4a695a',
        'on-secondary-fixed': '#022115',
        'on-secondary-fixed-variant': '#2f4d3f',
        'tertiary': '#555f73',
        'tertiary-container': '#97a1b8',
        'tertiary-fixed': '#d9e3fb',
        'tertiary-fixed-dim': '#bdc7de',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#2e384b',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3d475a',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f0fdf1',
        'surface-dim': '#d0ddd2',
        'surface-bright': '#f0fdf1',
        'surface-tint': '#006e2d',
        'surface-variant': '#d9e6da',
        'surface-container': '#e4f1e5',
        'surface-container-low': '#eaf7eb',
        'surface-container-high': '#dfece0',
        'surface-container-highest': '#d9e6da',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#131e17',
        'on-surface-variant': '#3d4a3d',
        'inverse-surface': '#28332b',
        'inverse-on-surface': '#e7f4e8',
        'background': '#f0fdf1',
        'on-background': '#131e17',
        'outline': '#6d7b6c',
        'outline-variant': '#bccbb9',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'pulse-red': 'pulse-red 2s infinite',
        'subtle-pulse': 'subtle-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'dash-move': 'dashmove 10s linear infinite',
        'contagion': 'dash 1s linear infinite',
        shimmer: 'shimmer 1.5s infinite',
        'count-up': 'countUp 1s ease-out forwards',
        'slide-in-right': 'slideInRight 0.3s ease-out forwards',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        typewriter: 'typewriter 2s steps(40) forwards',
      },
      keyframes: {
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-16px)' },
          '100%': { transform: 'translateY(0px)' },
        },
        'pulse-red': {
          '0%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(186, 26, 26, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0)' },
        },
        'subtle-pulse': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '.85', transform: 'scale(0.98)' },
        },
        dashmove: {
          'to': { strokeDashoffset: '-100' },
        },
        dash: {
          'to': { strokeDashoffset: '-20' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        typewriter: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
      },
    },
  },
  plugins: [],
}
